# Generated by Django 3.1.2 on 2020-12-13 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mapbox_location_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=500)),
                ('category_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendorName', models.CharField(max_length=200, verbose_name='Vendor Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('phoneNumber', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('age', models.CharField(blank=True, max_length=2, null=True, verbose_name='Age')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('vendorImg', models.ImageField(default=None, null=True, upload_to='upload/', verbose_name='A picture of the vendor:')),
                ('location', mapbox_location_field.models.LocationField(map_attrs={})),
                ('address', models.CharField(max_length=2000000)),
                ('categoryId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='vendorDetails.category', verbose_name='What category of items does this vendor sell?')),
                ('creator', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
