# Generated by Django 3.1.2 on 2020-12-13 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendorDetails', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorprofile',
            old_name='address',
            new_name='addressloc',
        ),
    ]
