# Generated by Django 3.1.2 on 2020-12-13 08:50

from django.db import migrations, models
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorDetails', '0002_auto_20201213_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationFilterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationOfFilter', mapbox_location_field.models.LocationField(map_attrs={})),
            ],
        ),
    ]
