# Generated by Django 3.1.2 on 2020-12-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorDetails', '0002_auto_20201223_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationfiltermodel',
            name='locFilterZipcodeLoc',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
